content:
  - name: letters
    label: Letters
    type: collection
    path: src/content/letter/*
    view:
      fields: [title, letter, row, size, body]
    fields:
      - name: title
        label: Title
        type: string
      - name: letter
        label: Letter
        type: string
      - name: row
        label: Row
        type: number
      - name: size
        label: Size
        type: select
        options:
          values:
            - value: small
              label: Small
            - value: big
              label: Big
      - name: body
        label: Body
        type: rich-text