content:
  - name: letters
    label: Letters
    type: collection
    path: src/content/letter
    view:
      fields: [title, letter]
    fields:
      - name: title
        label: Title
        type: string
      - name: letter
        label: Letter
        type: string
      - name: size
        label: Size
        type: select
        options:
          values:
            - value: small
              label: Small
            - value: big
              label: Big