content:
  - name: letters
    label: Letters
    type: collection
    subfolders: false
    path: src/content/letter
    view:
      fields: [title, letter]
    fields:
      - name: title
        label: Title
        type: string
      - name: letter
        label: Letter
        type: string
      